### ISSUE TITLE
Typoscript template with dataprocessor: wrong rendering of content elements

### ISSUE THREAD

**Issue by klodeckl** [CodersCare/gridelements#10]
If using the typoscript template with dataprocessing (in combination with ext bootstrap_grids) the rendering of content elements inside a gridelements column is wrong. For example if the news extension category view is placed inside a grid container the list view is shown instead of the category view. Also a custom content element (with a dataprocessor) displays strange things in the frontend. If using the classic typoscript templates everything is displayed as expected.

**Comment by Cybercraft-GmbH** [comment]
Hi Bernhard. Did you configure the flexform handling of the Gridelements containers correctly? by default the resolve FlexForms into arrays, to be able to get all necessary values wihtin your Fluid template. If you are using FlexForm based plugins like News, you have to disable that feature.

See https://docs.typo3.org/p/gridelementsteam/gridelements/main/en-us/Chapters/DataProcessing/Index.html

**Comment by klodeckl** [comment]
I have set the following typoscript, but no change:

tt_content.gridelements_pi1 {

  dataProcessing {
      10 = GridElementsTeam\Gridelements\DataProcessing\GridChildrenProcessor
      10 {
          default {
              as = children
              # Default options of the grid children processor
              # Change them according to the needs of your layout
              # Read more about it in the TypoScript section of the manual
              # options {
              #    sortingDirection = ASC
              #    sortingField = sorting
              #    recursive = 0
                  resolveFlexFormData = 0
                  resolveChildFlexFormData = 0
              #    resolveBackendLayout = 1
              #    respectColumns = 1
              #    respectRows = 1
              #}
          }
      }
    }
  }

**Comment by Cybercraft-GmbH** [comment]
You need to uncomment the options part and the closing brace too, otherwise the setting will be applied one level up. ;-)
If it still does not work, make sure to do it for the particular container and not just for default. You can check if it works by putting 
<f:debug>{_all}</f:debug> into your Fluid template, so you can see if the pi_flexform field gets resolved or not.

**Comment by klodeckl** [comment]
Thanks, uncommenting helped ;)
But I need the flexform values with bootstrap_grids so I will use the classic typoscript way.
Can I find this in the documentation?

**Comment by Cybercraft-GmbH** [comment]
If bootstrap_grid is not based on dataprocessing yet, that's the only option you've got. In this case FlexForms should be no problem, because the classic template does not resolve FlexForms at all.

**Comment by klodeckl** [comment]
bootstrap_grids is based on dataprocessing (offers also both), but the values of the bootstrap_grids flexform won’t get into that template. No matter, the classic way works.
