### ISSUE TITLE
Roadmap gridelements for TYPO3 V11

### ISSUE THREAD

**Issue by akerssies** [CodersCare/gridelements#14]
I was wondering if there is a roadmap for the TYPO3 V11 release? :)

**Comment by msollmann** [comment]
We are waiting too. TYPO3 11 has been released one year ago...

**Comment by etobi** [comment]
@Cybercraft-GmbH @Coders-Care 
Can you please outline the roadmap for TYPO3v11/PHP8.x?
Do you need support or testing?
How could we gain access to the "early access repo"?

**Comment by Bunnyfield** [comment]
The opportunity to update projects to CMS 11 and (up to) PHP 8.1 is already available for those who are or have been willing to join the crowd of supporting sponsors via https://coders.care/for/crowdfunding/gridelements/support

Additionally there is an article about why we won't publish any official date for a public release on Coders Care too:
https://coders.care/blog/article/not-as-in-free-beer

**Comment by etobi** [comment]
> The opportunity to update projects to CMS 11 and (up to) PHP 8.1 is already available for those who are or have been willing to join the crowd of supporting sponsors via https://coders.care/for/crowdfunding/gridelements/support
> 
> Additionally there is an article about why we won't publish any official date for a public release on Coders Care too: https://coders.care/blog/article/not-as-in-free-beer

Thanks for the hint to the blog post - I didnt saw that yet. Maybe put a link on the Crowdfunding-page?
I will check with my clients to support the campaign.

**Comment by sypets** [comment]
Also, this looks a bit outdated, maybe remove it?

> In case no milestone will be reached until end of January 2022, you will not get an invoice and the contract becomes obsolete.

https://coders.care/for/crowdfunding/gridelements/support

(personal opinion: more extension authors have made some additional features (e.g. news, typo3-solr) or the latest version (gridelements) available as paid version only. I find it a pity, that not more people just pay voluntarily for something they base their entire business model on and make money off of. For us as universities, this is not easily possible so we usually only pay when we have to (but even so, we have supported extensions both financially and via PR). But agencies have more freedom where they spend their money and they could help. If you look at the amount of work which goes into this extension or into news and the very few people who support it and also the contributions people like Jo or Georg Ringer do to keep things running, the numbers don't add up.)
