### ISSUE TITLE
TypeError substr(): Argument #1 ($string) must be of type string, int given when creating new CE Backend Layout

### ISSUE THREAD

**Issue by dkochdmk** [CodersCare/gridelements#28]
When creating a new CE backend layout in the TYPO3 backend, the above error is thrown. 

The error is in the GridelementsBackendLayoutWizardElement.php and GridelementsBackendLayoutWizardElement10.php when substr  $contentType['key'] and/or $listType['key'] without checking the key is a string.

**Comment by dkochdmk** [comment]
For example, tt_news uses an integer as the plugin identifier when it adds itself as a content element. Since there is no restriction in the addPlugin implementation to use a string for the identifier, this error may occur repeatedly.

**Comment by Bunnyfield** [comment]
OK - so this might be happening with legacy extensions mostly, which is why no one noticed it on our testing server.
