### ISSUE TITLE
CE context menu not working with activated gridelements 9.x

### ISSUE THREAD

**Issue by loeffe1** [CodersCare/gridelements#4]
The context menu that would normally show up when clicking the icon of a content element will no longer show as soon as I activate the v9.x release of this extension.

I am talking about the menu that should show when clicking this icon for example: 
![grafik](https://user-images.githubusercontent.com/42471369/185566984-fe31ef18-b684-4b7d-8cd7-a2326ff8d6bd.png)

**Comment by Bunnyfield** [comment]
Since Gridelements 9.x is not supported anymore please update to at least 10.x or even better 11.x and reopen the issue, if it is still valid with those versions.
