### ISSUE TITLE
TYPO3 v12 compatibility

### ISSUE THREAD

**Issue by romyschmidt** [CodersCare/gridelements#41]
Can you already give a date when the extension will be compatible for TYPO3 v12?

**Comment by mmasmoudi** [comment]
I have the same question, i want to know if Gridelements will have a new upgrade for TYPO3 v12 release ?

**Comment by mathias-heilmann** [comment]
Meanwhile we switched to [container](https://github.com/b13/container). Here some inspiration: https://codeblog.at/migration-von-gridelements-zu-container/ (sorry, only german)

**Comment by Cybercraft-GmbH** [comment]
You can find a detailed description of the development and release process here:
https://coders.care/blog/article/together-we-grow

TL;DR If you want to get a version, that's already working with CMS 12, you should consider sponsoring the development to get access to our Early-Access-Repositories.

**Comment by Bunnyfield** [comment]
@vnc-stel Please use the contact information page and call us or send us your data via contact form, so @PetraCyber can call you back.
https://coders.care/contact/get-in-touch
