### ISSUE TITLE
"Copy content from another page to this place" is not working in typo3 11

### ISSUE THREAD

**Issue by tomashavner** [CodersCare/gridelements#5]
The button "Copy content from another page to this place" is not working in Typo3 11. The reason is that GridElementsOnReady.js uses setFormValueFromBrowseWin which does not exist in version 11.

Kind regards

Tomas

**Comment by tomashavner** [comment]
No, I have not made any changes.

**Comment by Cybercraft-GmbH** [comment]
The current state of any public branch is not supposed to be working with CMS 11, especially when it comes to PHP 8.x compatibility.

There is an Early Access Repository though, that contains branches which are already widely compatible to CMS 11. Supporters of our crowdfunding campaigns will get access to that repository. Most of the issues like this are already tackled there.
Everybody else will have to wait for the public release of Gridelements 11.

You can find the crowdfunding form here: https://coders.care/for/crowdfunding/gridelements
