### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by BobMali** [CodersCare/gridelements#7]
Since TYPO3 v11 supports php 8 i suggest that gridelements should to. Mainly a few warnings that are being converted into exceptions in TYPO3 v11 with php 8 prevent this compatibility.
I created a MR to fix these exceptions. #6

**Comment by Cybercraft-GmbH** [comment]
Thanks a lot for your contribution, but there already is an early access repository where we are creating a new version of Gridelements, that is already compatible to both - CMS 10 and 11 - and both - PHP 7.x and 8x - too.

Since this version will tackle the issue we will close the PR here.
