### ISSUE TITLE
TYPO3 12 LTS / 13 LTS

### ISSUE THREAD

**Issue by cjanody** [CodersCare/gridelements#72]
Hi guys,

We are planning to upgrade our TYPO3 version and we would like to know if you plan to support the latest TYPO3 versions?

Thank you very much for your time.
Regards,

**Comment by bitwelle** [comment]
There is a TYPO3 12 version out there but looks like its not for the public. You have to pay to get access.
https://coders.care/for/crowdfunding/gridelements
Maybe the better and faster solution is to take a look into containers. Or am i wrong and a release is planned for public use?

**Comment by Bunnyfield** [comment]
@cjanody @bitwelle Maybe this blog post helps to clarify the state of Gridelements and other extensions we are maintaining.
https://coders.care/blog/article/together-we-grow

So the answer is: Yes, we are planning to support latest TYPO3 versions and we already do so for TYPO3 CMS 12. But this version is not made public yet. Development for Gridelements 13 will start soon and follow the same rules as described in the in the blog post.

**Comment by bitwelle** [comment]
Did I misunderstand that or shouldn't there now also be a public version for the old LTS v12 because of the official LTS v13 version? Or will there no more public versions?
